# Tech Watch Configuration

email:
  to: "abdelhadi.jbilou@gmail.com"
  
  # Gmail SMTP - Use App Password (NOT regular password)
  # Generate at: https://myaccount.google.com/apppasswords
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  smtp_username: "abdelhadi.jbilou@gmail.com"
  smtp_password: "mxov ysgs awtj esss"
  from_email: ""

output:
  folder: "./reports"
  days_back: 2
  retention_days: 30
  smart_summary: true
  summary_max_length: 300

# RSS Feeds Configuration
# OPTION 1: Use external file (recommended for easy maintenance)
# feeds_config_file: "feeds_config.yaml"

# OPTION 2: Define feeds inline (current setup)
rss_feeds:
  # Azure Security
  azure_security:
    - name: "Microsoft Security Response Center"
      url: "https://msrc.microsoft.com/blog/feed"
      keywords: ["azure"]
    - name: "Azure Security Blog"
      url: "https://azure.microsoft.com/en-us/blog/topics/security/feed/"
      keywords: []
    - name: "Azure Updates - Security"
      url: "https://azurecomcdn.azureedge.net/en-us/updates/feed/"
      keywords: ["security", "compliance", "defender", "sentinel"]
  
  # Azure Architecture
  azure_architecture:
    - name: "Azure Architecture Blog"
      url: "https://techcommunity.microsoft.com/gxcuf89792/rss/board?board.id=AzureArchitectureBlog"
      keywords: []
    - name: "Azure Updates - Architecture"
      url: "https://azurecomcdn.azureedge.net/en-us/updates/feed/"
      keywords: ["architecture", "design", "pattern", "best practices"]
  
  # Azure Blog
  azure_blog:
    - name: "Azure Blog - General"
      url: "https://azure.microsoft.com/en-us/blog/feed/"
      keywords: []
    - name: "Azure DevOps Blog"
      url: "https://devblogs.microsoft.com/devops/feed/"
      keywords: []
  
  # Azure Database
  azure_database:
    - name: "Azure Database Blog"
      url: "https://techcommunity.microsoft.com/gxcuf89792/rss/board?board.id=AzureDatabaseBlog"
      keywords: []
    - name: "Azure SQL Blog"
      url: "https://techcommunity.microsoft.com/gxcuf89792/rss/board?board.id=AzureSQLBlog"
      keywords: []
    - name: "Azure Updates - Database"
      url: "https://azurecomcdn.azureedge.net/en-us/updates/feed/"
      keywords: ["sql", "database", "cosmos", "postgresql", "mysql"]
  
  # Azure App Services
  azure_app_services:
    - name: "Azure App Service Blog"
      url: "https://azure.github.io/AppService/feed.xml"
      keywords: []
    - name: "Azure Updates - App Services"
      url: "https://azurecomcdn.azureedge.net/en-us/updates/feed/"
      keywords: ["app service", "web app", "function", "container apps"]
  
  # Terraform
  terraform:
    - name: "HashiCorp Terraform Blog"
      url: "https://www.hashicorp.com/blog/products/terraform/rss.xml"
      keywords: []
    - name: "Terraform AzureRM Provider Releases"
      url: "https://github.com/hashicorp/terraform-provider-azurerm/releases.atom"
      keywords: []
    - name: "Terraform Core Releases"
      url: "https://github.com/hashicorp/terraform/releases.atom"
      keywords: []
  
  # HashiCorp
  hashicorp:
    - name: "HashiCorp Blog"
      url: "https://www.hashicorp.com/blog/rss.xml"
      keywords: ["azure", "cloud", "infrastructure"]
    - name: "HashiCorp Announcements"
      url: "https://www.hashicorp.com/blog/categories/announcements/rss.xml"
      keywords: []
  
  # GitHub Actions
  github_actions:
    - name: "GitHub Actions Changelog"
      url: "https://github.blog/changelog/label/actions/feed/"
      keywords: []
    - name: "GitHub Blog - Actions"
      url: "https://github.blog/feed/"
      keywords: ["actions", "workflow", "ci/cd", "runner"]
    - name: "GitHub Actions Releases"
      url: "https://github.com/actions/runner/releases.atom"
      keywords: []
